### ISSUE TITLE
ASP.NET-MVC Database source config is incorrectly pointed to in README

### ISSUE THREAD

**Issue by gannonprudhomme** [SpecFlowOSS/SpecFlow-Examples#30]
In the ASP.NET MVC example, the README states that the connection string for the local database is in BookShop.Mvc/Web.Config, when it is actually located in BookShop.Mvc/Models/DatabaseContext.cs 's constructor.

Where it says it is, per the README:
`Update the connection string in web.config (project BookShop.Mvc) and app.config (project BookShop.AcceptanceTests) in the <add name="BookShopEntities"/> element: The default setting points to a (localdb) instance:`

[Where it actually is](https://github.com/techtalk/SpecFlow-Examples/blob/master/ASP.NET-MVC/BookShop/BookShop.Mvc/Models/DatabaseContext.cs)

**Comment by SabotageAndi** [comment]
We migrated the bookshop example to ASP.NET Core and rewrote the readme => closed.
