### ISSUE TITLE
BowlingKata-Fsharp Bowling.SpecFlow.Bindings.csproj needs to copy specflow.json to output dir

### ISSUE THREAD

**Issue by mscham** [SpecFlowOSS/SpecFlow-Examples#41]
I would submit a pull request but I don't know how to.  
Without the below all tests will fail with step definition cannot be found messages.

specflow.json should be set to 'Copy to output directory' - 'Copy Always' in the proj file:

  <ItemGroup>
    <None Update="specflow.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

**Comment by beerai** [comment]
Any idea how to make the extension stop complaining that the step definitions can't be found in the feature file?

**Comment by SabotageAndi** [comment]
@beerai The navigation has some problems when the step definitions are in another project. That is an issue with the Visual Studio Extension.
