### ISSUE TITLE
LivingDoc

### ISSUE THREAD

**Issue by santhosh-James** [SpecFlowOSS/SpecFlow-Examples#58]
I installed the nugget package specflow.plus.LivingDoc nuget and execute the tests. Looks like it is generating a file called TestExecution.json in the output directory. And when I execute the command line LivingDoc.exe c:\bin\debug\netcoreapp3.1\Testexecution.Json I get the error saying 

Required command was not provided.
Unrecognized command or argument ‘TestExecution.json’ 

What I am missing here? I don’t see featuredata.json in output directory

**Comment by SabotageAndi** [comment]
@santhosh-James this is the repo for examples, so the completely wrong place. 
A better place is the community forum for such questions: https://support.specflow.org/hc/en-us/community/topics
